"""empty message

Revision ID: 382ef9984273
Revises: dc9d331c8bf3
Create Date: 2024-03-16 20:09:02.639806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382ef9984273'
down_revision = 'dc9d331c8bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_clients_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('appointment_datetime', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_appointments_client_id_clients')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_appointments_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('waive_and_release', sa.Boolean(), nullable=False),
    sa.Column('questions', sa.Boolean(), nullable=False),
    sa.Column('aftercare', sa.Boolean(), nullable=False),
    sa.Column('drugs_or_booze', sa.Boolean(), nullable=False),
    sa.Column('health_conditions', sa.String(), nullable=False),
    sa.Column('spelling_responsibility', sa.Boolean(), nullable=False),
    sa.Column('no_refund', sa.Boolean(), nullable=False),
    sa.Column('attorney_fees', sa.Boolean(), nullable=False),
    sa.Column('photographic_consent', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('street_address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('date_signed', sa.DateTime(), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_consent_forms_client_id_clients')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consent_forms')
    op.drop_table('appointments')
    op.drop_table('clients')
    # ### end Alembic commands ###
